# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: clp's site
email: lucaspng@aol.com
description: > # this means to ignore newlines until "baseurl:"
  Lucas' personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://clp93.github.io" # the base hostname & protocol for your site
twitter_username: chlpng
github_username:  clp93

# Build settings
markdown: kramdown
